super_spine:
  defaults:
    bgp_as: 65000
    loopback_ipv4_pool: 192.168.99.0/24
    loopback_ipv6_pool: 2000:db8::/64
    evpn_role: server
  nodes:
    DCI:  
      id: 1
      mgmt_ip: 192.168.0.76/24
super_spine_bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200