---

fabric_name: FABRIC

# Various fabric settings

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: true
underlay_multicast: true 
evpn_multicast: true

# There's an issue with vEOS with larger MTUs
p2p_uplinks_mtu: 1500

# Needed for Arista ATD Lab Environment
dns_domain: atd.lab
mgmt_interface: Management0
mgmt_interface_vrf: default
mgmt_gateway: 192.168.0.1
