dc_name: DC1
max_super_spines: 4
max_spine_to_super_spine_links: 4
super_spine:
  defaults:
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.99.0/24
    loopback_ipv6_pool: 2005:db8::/64
    evpn_role: server
  nodes:
    superspine1:  
      id: 201
      mgmt_ip: 192.168.0.25/24
    superspine2:  
      id: 202
      mgmt_ip: 192.168.0.26/24
super_spine_bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
